[book]
authors = ["Mote Contributors"]
language = "en"
src = "src"
title = "Mote Docs"

[output.html]
default-theme = "night"
preferred-dark-theme = "night"
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/empriselab/mote"
edit-url-template = "https://github.com/empriselab/mote/tree/main/mote-book/{path}"
# sidebar-header-nav = false
