[default]
_default:
    just --list

build:
    just -f ../mote-ffi/justfile build-wasm
    npm install
    npm run generate-types

run-dev: build
    npx vite

test: build
    npm run test:run

ci: build
    npm run check
    npm run test:run

ci-build: build
    npm ci
    npm run build
    npm run check
